apiVersion: apps/v1
kind: Deployment
metadata:
  name: fargs-server
  labels:
    app: fargs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fargs-server
  template:
    metadata:
      name: fargs-server
      labels:
        app: fargs-server
    spec:
      containers:
        - name: fargs-server
          image: ghcr.io/filian-arg-map-scanner/fargsserver:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: fargs-server-config
      restartPolicy: Always
      