name: build
on:
  push:
    tags-ignore:
      - '*'
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.7.0
        with:
          versionSpec: '6.8.x'
      - name: Determine Version
        id: version_step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v4.7.0
      - name: Set Version
        run: echo "VERSION=${{ steps.version_step.outputs.semVer }}" >> $GITHUB_ENV
      - name: Use Node.js 22.23.2
        uses: actions/setup-node@v7
        with:
          node-version: 22.23.2
      - name: install Yarn
        run: npm i -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn run sentry:sourcemaps
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
      - run: tar -xzf ${{steps.version_step.outputs.semVer}}.tar.gz dist package.json yarn.lock
      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
        with:
          environment: production
          release: ${{steps.version_step.outputs.fullSemVer}}
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{steps.version_step.outputs.fullSemVer}}',
              sha: context.sha
            })
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{steps.version_step.outputs.fullSemVer}}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
          files: |
            ${{steps.version_step.outputs.semVer}}.tar.gz
