name: build
on:
  push:
    tags-ignore:
      - '*'
    branches:
      - master

jobs:
  version:
    runs-on: pve-cluster-runners
    outputs:
      version: ${{steps.version_step.outputs.semver}}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Set DOTNET_INSTALL_DIR
        run: echo "DOTNET_INSTALL_DIR=$RUNNER_TOOL_CACHE/dotnet" >> $GITHUB_ENV
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.7.0
        with:
          versionSpec: '6.8.x'
      - name: Determine Version
        id: version_step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v4.7.0
      - name: Set Version
        run: echo "SEMVER=${{ steps.version_step.outputs.semVer }}" >> $GITHUB_OUTPUT
  build:
    runs-on: pve-cluster-runners
    needs: version
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Use Node.js 22.23.2
        uses: actions/setup-node@v7
        with:
          node-version: 22.23.2
          package-manager-cache: 'false'
      - name: install Yarn
        run: npm i -g yarn
      - uses: actions/cache@v6
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - run: yarn install --frozen-lockfile --production=false
      - run: yarn build
        env:
          NODE_ENV: production
      - run: yarn run sentry:sourcemaps
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
      - name: Upload built js
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist/
  build-docker:
    runs-on: pve-cluster-runners-dind
    needs:
      - version
      - build
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      artifact-metadata: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Download built tar
        uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist/
      - name: Use Node.js 22.23.2
        uses: actions/setup-node@v7
        with:
          node-version: 22.23.2
          package-manager-cache: 'false'
      - name: install Yarn
        run: npm i -g yarn
      - uses: actions/cache@v6
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - run: yarn install --frozen-lockfile --production=true
      - name: Log in to the Container registry
        uses: docker/login-action@v4.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6.2.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=${{needs.version.outputs.version}}
            type=sha
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v7.4.0
        with:
          context: .
          push: true
          cache-to: type=gha
          cache-from: type=gha
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secret-envs: |
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
            SENTRY_ORG=${{ vars.SENTRY_ORG }}
            SENTRY_PROJECT=${{ vars.SENTRY_PROJECT }}
      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
  create-release:
    runs-on: pve-cluster-runners-dind
    needs:
      - version
      - build
      - build-docker
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Download built tar
        uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist/
      - run: tar -czf ${{needs.version.outputs.version}}.tar.gz dist package.json yarn.lock
      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
        with:
          environment: production
          release: ${{needs.version.outputs.version}}
      - name: Create tag
        uses: actions/github-script@v9
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{needs.version.outputs.version}}',
              sha: context.sha
            })
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{needs.version.outputs.version}}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
          files: |
            ${{needs.version.outputs.version}}.tar.gz
      # Action to log into Octopus Deploy
      - name: Login to Octopus Deploy
        uses: OctopusDeploy/login@v1
        with:
          server: https://octopus.bibbythe.dev
          service_account_id: a1e8348c-2213-4384-838b-fb6adae5ff85
      - name: Create a Zip package 🐙
        id: create_a_zip_package
        uses: OctopusDeploy/create-zip-package-action@v4
        with:
          package_id: 'FargsServer'
          version: ${{needs.version.outputs.version}}
          output_folder: './packaging'
          base_path: .
          files: |
            dist/**/*.*
            package.json
            yarn.lock
            kubernetes/*.*
      - name: Push a package to Octopus Deploy 🐙
        id: push_a_package_to_octopus_deploy
        uses: OctopusDeploy/push-package-action@v4
        env:
          OCTOPUS_SPACE: 'Default'
        with:
          packages: |
            packaging/**/*.zip
      # Action to Create a Release
      - name: Create a release in Octopus Deploy 🐙
        uses: OctopusDeploy/create-release-action@v3
        env:
          OCTOPUS_SPACE: 'Default'
        with:
          project: 'fargs-server'
          release_number: ${{needs.version.outputs.version}}
          git_ref: ${{ github.head_ref || github.ref }}
          git_commit: ${{ github.event.pull_request.head.sha || github.sha }}

      # Action to Deploy a Release
      - name: Deploy a release in Octopus Deploy 🐙
        uses: OctopusDeploy/deploy-release-action@v3
        env:
          OCTOPUS_SPACE: 'Default'
        with:
          project: 'fargs-server'
          release_number: ${{needs.version.outputs.version}}
          environments: |
            Development